### PR TITLE
Updated readme and removed the local user guide - for 3.19.0 release

### PR DESCRIPTION
**Pull request by ivan-gravitee**
Updated readme and removed the local user guide - for 3.19.0 release.

Readme now has links referencing the public GKO docs.

### CODE REVIEW

**Comment by ThibaudAV** [comment]
haha, We can add in contributing : 
This repo use [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/) and semantic release

Thats why the ci ⬆️ failed

**Comment by ivan-gravitee** [comment]
> This repo use [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/) and semantic release

Indeed, let me add it:)

**Comment by a-cordier** [comment]
@ivan-gravitee would you mind squashing the commits into one semantic commit in order to get the PR pass the checks ?

something like

```
docs: update readme and remove user guide
```

**Review by a-cordier — APPROVED** [review]

**Pull request merged**
