### PR TITLE
set tolerations for gko-controller-manager

### PR DESCRIPTION
**Pull request by lucamaggioni**
set tolerations for gko-controller-manager

### CODE REVIEW

**Comment by a-cordier** [comment]
Hello @lucamaggioni thanks for the contribution !

We use a commit linter in our ci chain, which unfortunately does not run on forks right now

Could you please rebase your commits and use the [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/) syntax ?

something like 
```
feat: set tolerations for gko-controller-manager deployment
```

**Review by a-cordier — APPROVED** [review]
Looks good to me, but the history needs a rewrite otherwise commit lint will fail

**Comment by lucamaggioni** [comment]
I've openend https://github.com/gravitee-io/gravitee-kubernetes-operator/pull/863 in a new non-forked feature branch, but conflictsarise  with this (https://github.com/gravitee-io/gravitee-kubernetes-operator/pull/863#issuecomment-2404706938).

What do we do?
Close this one?
Do I have to do things differently?

**Comment by a-cordier** [comment]
Hi @lucamaggioni I can see that you edited the commit, last commit, thank you for that, but we don't use squash and merge on this repo so can you squash those 3 commits locally so that I can merge ? After that we are done I promise :) 

Thanks again!

**Comment by lucamaggioni** [comment]
I think I have done what you asked... Check it out and please tell me if is it ok.

**Comment by a-cordier** [comment]
> I think I have done what you asked... Check it out and please tell me if is it ok... but.. again we are in a fork ... is it a problem?

Perfect thanks! Could you just rebase the commit on master and we will be good.

I tested your PR myself so we can merge, we created a task to enable ci runs on PR, I will get into it ASAP.

**Comment by lucamaggioni** [comment]
> Perfect thanks! Could you just rebase the commit on master and we will be good (there's a conflict)

I've done it... did I've done it right? :)

**Comment by a-cordier** [comment]
> > Perfect thanks! Could you just rebase the commit on master and we will be good (there's a conflict)
> 
> I've done it... did I've done it right? :)

Hello @lucamaggioni sorry for the late feedback but with been busy with something else lately.

Yes, I just gave a test to your pull request and it works just fine.

Again, thanks for contributing to the project.

We created a ticket to provide a better experience when it comes to contributing from a fork.

**Review by a-cordier — APPROVED** [review]
👍

**Pull request merged**
