### PR TITLE
Update and rename README.adoc to README.md

### PR DESCRIPTION
**Pull request by jackripper235**

### CODE REVIEW

**Comment by jackripper235** [comment]
@jackripper235

**Review by jackripper235 — COMMENTED** [review]
@jackripper235

**Comment by a-cordier** [comment]
Hello @jackripper235 can we assume that this PR can be closed ? It looks very much like a test. Thanks!

**Comment by a-cordier** [comment]
@jackripper235 I closed the PR, assuming that it was indeed the result of some kind of testing.

**Pull request closed without merging**
